name: Run tests
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Install Wireshark & tshark
        run: |
          echo "wireshark-common wireshark-common/install-setuid boolean true" | debconf-set-selections
          DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -y install wireshark
          apt-get update && apt-get install -y --allow-change-held-packages --force-yes tshark
      - name: Run pytest
        run: |
          pytest